version: '3'

services:

  apache-php:
    image: ${IMAGE}:${IMAGE_VERSION}
    hostname: ${SHOP_HOSTNAME}
    restart: always
    depends_on:
      - mysql
    volumes:
      - ${PWD}/data/www:/var/www/
    env_file:
      - .env
    ports:
      - "${APACHE_PORT}:80"
      - "${APACHE_HTTPS_PORT}:443"
      - "${MAILCATCHER_PORT}:1080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${SHOP_TYPE}${SHOP_VERSION}

  mysql:
    image: mariadb:5.5
    hostname: mysql.${DOMAIN}
    restart: always
    volumes:
      - ${PWD}/data/www/${SHOP_TYPE}${SHOP_VERSION}/${SHOP_TYPE}${SHOP_VERSION}.sql:/docker-entrypoint-initdb.d/${SHOP_TYPE}${SHOP_VERSION}.sql
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306

volumes:
  mysql-data:
